# Funding links for the Sponsor button on GitHub.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# GitHub Sponsors: enroll at https://github.com/sponsors (required for github: below).
# Uncomment and set any other platforms you use.

github: cloudbadal007

# patreon: your_patreon_username
# open_collective: your_collective
# ko_fi: your_kofi_username
# buy_me_a_coffee: your_bmac_username
# liberapay: your_liberapay_username
# tidelift: platform/package
# issuehacker: your_username
# otechie: your_username
# lfx_crowdfunding: project-name

# custom:
#   - https://www.paypal.me/yourname
#   - https://buymeacoffee.com/yourname
